# Generated by Django 4.2.7 on 2025-01-24 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
    ]
