# Generated by Django 4.2.7 on 2025-01-24 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_code_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='tax',
            name='qr',
            field=models.TextField(blank=True, null=True),
        ),
    ]
